from enum import Enum


class PortfolioAllocationLegAssociationConsistencyApplicabilityStatus(Enum):
    ALLOCATION_LEG_ENDPOINT_MISMATCH = "ALLOCATION_LEG_ENDPOINT_MISMATCH"
    RISK_BUDGET_ENDPOINT_MISMATCH = "RISK_BUDGET_ENDPOINT_MISMATCH"
    CAPITAL_BUCKET_ENDPOINT_MISMATCH = "CAPITAL_BUCKET_ENDPOINT_MISMATCH"
    APPLICABLE = "APPLICABLE"
