from __future__ import annotations

# Wake / trigger types — JOO-domain only; AI cannot invent wakes without evidence.
WAKE_PORTFOLIO_MEMBERSHIP_CHANGED = "PORTFOLIO_MEMBERSHIP_CHANGED"
WAKE_PORTFOLIO_QUANTITY_CHANGED = "PORTFOLIO_QUANTITY_CHANGED"
WAKE_CAPITAL_ORDERABLE_CASH_CHANGED = "CAPITAL_ORDERABLE_CASH_CHANGED"
WAKE_RESEARCH_EVIDENCE_ADMITTED = "RESEARCH_EVIDENCE_ADMITTED"
WAKE_THESIS_TRANSITION = "THESIS_TRANSITION"
WAKE_POLICY_SUPERSEDED = "POLICY_SUPERSEDED"
WAKE_APPROVAL_TRANSITION = "APPROVAL_TRANSITION"
WAKE_BROKER_ORDER_OR_FILL = "BROKER_ORDER_OR_FILL"
WAKE_SUBMISSION_OUTCOME_UNKNOWN = "SUBMISSION_OUTCOME_UNKNOWN"
WAKE_RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
WAKE_PROVIDER_FAILURE = "PROVIDER_FAILURE"
WAKE_RECOVERY_RESUME = "RECOVERY_RESUME"

WAKE_TYPES = frozenset({
    WAKE_PORTFOLIO_MEMBERSHIP_CHANGED,
    WAKE_PORTFOLIO_QUANTITY_CHANGED,
    WAKE_CAPITAL_ORDERABLE_CASH_CHANGED,
    WAKE_RESEARCH_EVIDENCE_ADMITTED,
    WAKE_THESIS_TRANSITION,
    WAKE_POLICY_SUPERSEDED,
    WAKE_APPROVAL_TRANSITION,
    WAKE_BROKER_ORDER_OR_FILL,
    WAKE_SUBMISSION_OUTCOME_UNKNOWN,
    WAKE_RECONCILIATION_MISMATCH,
    WAKE_PROVIDER_FAILURE,
    WAKE_RECOVERY_RESUME,
})

# Explicit operational stages (existing product boundaries). No stage skip.
STAGE_FACT_REFRESH = "FACT_REFRESH"
STAGE_PORTFOLIO_SNAPSHOT = "PORTFOLIO_SNAPSHOT"
STAGE_CAPITAL_SNAPSHOT = "CAPITAL_SNAPSHOT"
STAGE_RESEARCH = "RESEARCH"
STAGE_SEMANTIC_ADMISSION = "SEMANTIC_ADMISSION"
STAGE_THESIS = "THESIS"
STAGE_EXPECTED_VALUE = "EXPECTED_VALUE"
STAGE_CIO = "CIO"
STAGE_CAPITAL_ALLOCATION = "CAPITAL_ALLOCATION"
STAGE_INVESTMENT_HUMAN_GATE = "INVESTMENT_HUMAN_GATE"
STAGE_PRETRADE = "PRETRADE"
STAGE_TRADE_HUMAN_GATE = "TRADE_HUMAN_GATE"
STAGE_BROKER_STATUS = "BROKER_STATUS"
STAGE_RECONCILIATION = "RECONCILIATION"

STAGE_ORDER = (
    STAGE_FACT_REFRESH,
    STAGE_PORTFOLIO_SNAPSHOT,
    STAGE_CAPITAL_SNAPSHOT,
    STAGE_RESEARCH,
    STAGE_SEMANTIC_ADMISSION,
    STAGE_THESIS,
    STAGE_EXPECTED_VALUE,
    STAGE_CIO,
    STAGE_CAPITAL_ALLOCATION,
    STAGE_INVESTMENT_HUMAN_GATE,
    STAGE_PRETRADE,
    STAGE_TRADE_HUMAN_GATE,
    STAGE_BROKER_STATUS,
    STAGE_RECONCILIATION,
)

# Predecessor requirements: a stage may run only if all predecessors completed
# or were not required for this wake. Required chain for research/CIO path.
STAGE_PREDECESSORS = {
    STAGE_FACT_REFRESH: (),
    STAGE_PORTFOLIO_SNAPSHOT: (STAGE_FACT_REFRESH,),
    STAGE_CAPITAL_SNAPSHOT: (STAGE_FACT_REFRESH,),
    STAGE_RESEARCH: (STAGE_PORTFOLIO_SNAPSHOT,),
    STAGE_SEMANTIC_ADMISSION: (STAGE_RESEARCH,),
    STAGE_THESIS: (STAGE_SEMANTIC_ADMISSION,),
    STAGE_EXPECTED_VALUE: (STAGE_THESIS,),
    STAGE_CIO: (STAGE_EXPECTED_VALUE,),
    STAGE_CAPITAL_ALLOCATION: (STAGE_CIO, STAGE_CAPITAL_SNAPSHOT),
    STAGE_INVESTMENT_HUMAN_GATE: (STAGE_CAPITAL_ALLOCATION,),
    STAGE_PRETRADE: (STAGE_INVESTMENT_HUMAN_GATE,),
    STAGE_TRADE_HUMAN_GATE: (STAGE_PRETRADE,),
    STAGE_BROKER_STATUS: (STAGE_FACT_REFRESH,),
    STAGE_RECONCILIATION: (STAGE_BROKER_STATUS,),
}

# Human attention categories (safety-critical priority, not investment ranking).
ATTENTION_INVESTMENT_APPROVAL_REQUIRED = "INVESTMENT_APPROVAL_REQUIRED"
ATTENTION_TRADE_AUTHORIZATION_REQUIRED = "TRADE_AUTHORIZATION_REQUIRED"
ATTENTION_THESIS_INVALIDATED = "THESIS_INVALIDATED"
ATTENTION_ALLOCATION_REVISION_REQUIRED = "ALLOCATION_REVISION_REQUIRED"
ATTENTION_SUBMISSION_OUTCOME_UNKNOWN = "SUBMISSION_OUTCOME_UNKNOWN"
ATTENTION_RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
ATTENTION_PROVIDER_FAILURE = "PROVIDER_FAILURE"
ATTENTION_POLICY_CONFLICT = "POLICY_CONFLICT"
ATTENTION_DATA_INTEGRITY_FAILURE = "DATA_INTEGRITY_FAILURE"
ATTENTION_OPEN_LIMIT_REQUIRES_HUMAN = "OPEN_LIMIT_REQUIRES_HUMAN"

ATTENTION_PRIORITY = {
    ATTENTION_DATA_INTEGRITY_FAILURE: 0,
    ATTENTION_SUBMISSION_OUTCOME_UNKNOWN: 1,
    ATTENTION_OPEN_LIMIT_REQUIRES_HUMAN: 2,
    ATTENTION_RECONCILIATION_MISMATCH: 3,
    ATTENTION_PROVIDER_FAILURE: 4,
    ATTENTION_POLICY_CONFLICT: 5,
    ATTENTION_TRADE_AUTHORIZATION_REQUIRED: 6,
    ATTENTION_INVESTMENT_APPROVAL_REQUIRED: 7,
    ATTENTION_THESIS_INVALIDATED: 8,
    ATTENTION_ALLOCATION_REVISION_REQUIRED: 9,
}

STAGE_STATUS_COMPLETED = "COMPLETED"
STAGE_STATUS_SKIPPED = "SKIPPED"
STAGE_STATUS_FAILED = "FAILED"
STAGE_STATUS_PENDING = "PENDING"
STAGE_STATUS_BLOCKED = "BLOCKED"

CHECKPOINT_COMPLETE = "COMPLETE"
CHECKPOINT_PARTIAL = "PARTIAL"
CHECKPOINT_FAILED = "FAILED"
CHECKPOINT_RESUME_SAFE = "RESUME_SAFE"

IDEMPOTENCY_HIT = "IDEMPOTENCY_HIT"
IDEMPOTENCY_MISS = "IDEMPOTENCY_MISS"

OWNERSHIP_HELD = "HELD"
OWNERSHIP_DENIED = "DENIED"
OWNERSHIP_UNPROVABLE = "UNPROVABLE"

FAILURE_AI_WAKE_WITHOUT_EVIDENCE = "AI_WAKE_WITHOUT_EVIDENCE"
FAILURE_STAGE_SKIP = "STAGE_SKIP_FORBIDDEN"
FAILURE_LIVE_MUTATION_DISABLED = "LIVE_MUTATION_DISABLED"
FAILURE_DUPLICATE_DECISION = "DUPLICATE_DECISION_BLOCKED"
FAILURE_EXCLUSIVE_OWNERSHIP_UNPROVABLE = "EXCLUSIVE_OWNERSHIP_UNPROVABLE"
FAILURE_MISSING_NE_ZERO = "MISSING_NOT_ZERO_OR_SAFE"
FAILURE_AUTO_APPROVAL_FORBIDDEN = "AUTO_APPROVAL_FORBIDDEN"
FAILURE_GATE_MERGE_FORBIDDEN = "GATE_MERGE_FORBIDDEN"
FAILURE_RETRY_UNSAFE = "RETRY_UNSAFE"
FAILURE_PROVIDER_OUTAGE = "PROVIDER_OUTAGE_AS_DATA"
FAILURE_OVERLAPPING_CYCLE = "OVERLAPPING_SAME_EVENT_CYCLE"

# Bounded safe retries only (READ / projection). Never mutation/approval/TEA.
MAX_SAFE_RETRIES = 2

MUTATION_TRANSPORT_DEFAULT = "LIVE_DISABLED"

# Phase 4 durable ownership lease (implementation-level; not investment policy)
FAILURE_LEASE_CORRUPT = "OWNERSHIP_LEASE_CORRUPT"
FAILURE_LEASE_NOT_OWNER = "OWNERSHIP_LEASE_NOT_OWNER"
FAILURE_LEASE_PERSISTENCE = "OWNERSHIP_LEASE_PERSISTENCE_FAILURE"
FAILURE_LEASE_EXPIRED = "OWNERSHIP_LEASE_EXPIRED"
DURABLE_LEASE_TTL_SECONDS = 300  # crash/restart recovery bound only
