from enum import Enum


class PortfolioAllocationProposalPositionLinkApplicabilityStatus(Enum):
    ALLOCATION_PROPOSAL_ENDPOINT_MISMATCH = (
        "ALLOCATION_PROPOSAL_ENDPOINT_MISMATCH"
    )
    POSITION_ENDPOINT_MISMATCH = "POSITION_ENDPOINT_MISMATCH"
    RECOMMENDATION_ENDPOINT_MISMATCH = (
        "RECOMMENDATION_ENDPOINT_MISMATCH"
    )
    PORTFOLIO_SNAPSHOT_ENDPOINT_MISMATCH = (
        "PORTFOLIO_SNAPSHOT_ENDPOINT_MISMATCH"
    )
    PORTFOLIO_ENDPOINT_MISMATCH = "PORTFOLIO_ENDPOINT_MISMATCH"
    APPLICABLE = "APPLICABLE"
