from enum import Enum


class IRORunPhase(Enum):
    INITIALIZED = "INITIALIZED"
    SCANNED = "SCANNED"
    PLANNED = "PLANNED"
    ROUTED = "ROUTED"
    PROMPTS_FROZEN = "PROMPTS_FROZEN"
    EXECUTED = "EXECUTED"
    COLLECTED = "COLLECTED"
    STORED = "STORED"
    MEMORY_COMPARED = "MEMORY_COMPARED"
    COMPLETED = "COMPLETED"
    SHORT_CIRCUITED_NO_MATERIAL_DELTA = (
        "SHORT_CIRCUITED_NO_MATERIAL_DELTA"
    )
    FAILED = "FAILED"


class IRORunStatus(Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    SHORT_CIRCUITED_NO_MATERIAL_DELTA = (
        "SHORT_CIRCUITED_NO_MATERIAL_DELTA"
    )
    FAILED = "FAILED"


class ScanChangeClass(Enum):
    MEMBERSHIP_ADDED = "MEMBERSHIP_ADDED"
    MEMBERSHIP_REMOVED = "MEMBERSHIP_REMOVED"
    QUANTITY_CHANGED = "QUANTITY_CHANGED"
    BASELINE_ABSENT_SUBJECT = "BASELINE_ABSENT_SUBJECT"


class SubjectClass(Enum):
    HOLDING = "HOLDING"
    WATCHLIST = "WATCHLIST"


class MemoryDeltaClass(Enum):
    NO_PRIOR = "NO_PRIOR"
    UNCHANGED = "UNCHANGED"
    STATEMENT_CHANGED = "STATEMENT_CHANGED"
    ADDED = "ADDED"
    REMOVED = "REMOVED"


class EvidencePayloadKind(Enum):
    FINDING = "FINDING"
    COLLECTION_FAILURE = "COLLECTION_FAILURE"
    PROMPT_FREEZE = "PROMPT_FREEZE"
    EXECUTION_RECORD = "EXECUTION_RECORD"
    COMPLETENESS = "COMPLETENESS"
    RAW = "RAW"
