from enum import Enum


class IRORunPhase(Enum):
    INITIALIZED = "INITIALIZED"
    SCANNED = "SCANNED"
    PLANNED = "PLANNED"
    ROUTED = "ROUTED"
    PROMPTS_FROZEN = "PROMPTS_FROZEN"
    EXECUTED = "EXECUTED"
    COLLECTED = "COLLECTED"
    STORED = "STORED"
    MEMORY_COMPARED = "MEMORY_COMPARED"
    COMPLETED = "COMPLETED"
    SHORT_CIRCUITED_NO_MATERIAL_DELTA = (
        "SHORT_CIRCUITED_NO_MATERIAL_DELTA"
    )
    FAILED = "FAILED"
    CONTRADICTION_EVALUATED = "CONTRADICTION_EVALUATED"
    RE_RESEARCH_ADMITTED = "RE_RESEARCH_ADMITTED"
    ESCALATED_HUMAN_REVIEW = "ESCALATED_HUMAN_REVIEW"


class IRORunStatus(Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    SHORT_CIRCUITED_NO_MATERIAL_DELTA = (
        "SHORT_CIRCUITED_NO_MATERIAL_DELTA"
    )
    FAILED = "FAILED"
    ESCALATED_HUMAN_REVIEW = "ESCALATED_HUMAN_REVIEW"


class ScanChangeClass(Enum):
    MEMBERSHIP_ADDED = "MEMBERSHIP_ADDED"
    MEMBERSHIP_REMOVED = "MEMBERSHIP_REMOVED"
    QUANTITY_CHANGED = "QUANTITY_CHANGED"
    BASELINE_ABSENT_SUBJECT = "BASELINE_ABSENT_SUBJECT"


class SubjectClass(Enum):
    HOLDING = "HOLDING"
    WATCHLIST = "WATCHLIST"


class MemoryDeltaClass(Enum):
    NO_PRIOR = "NO_PRIOR"
    UNCHANGED = "UNCHANGED"
    STATEMENT_CHANGED = "STATEMENT_CHANGED"
    ADDED = "ADDED"
    REMOVED = "REMOVED"
    PROVENANCE_CHANGED = "PROVENANCE_CHANGED"
    MULTI_FINDING_SET_CHANGED = "MULTI_FINDING_SET_CHANGED"
    CONFIDENCE_GAP = "CONFIDENCE_GAP"


class EvidencePayloadKind(Enum):
    FINDING = "FINDING"
    COLLECTION_FAILURE = "COLLECTION_FAILURE"
    PROMPT_FREEZE = "PROMPT_FREEZE"
    EXECUTION_RECORD = "EXECUTION_RECORD"
    COMPLETENESS = "COMPLETENESS"
    RAW = "RAW"
    MEMORY_DELTA_SET = "MEMORY_DELTA_SET"
    CONTRADICTION_EVALUATION = "CONTRADICTION_EVALUATION"
    RE_RESEARCH_ADMISSION = "RE_RESEARCH_ADMISSION"
    ESCALATION = "ESCALATION"


class ContradictionCaseClass(Enum):
    NUMERIC_CANDIDATE = "NUMERIC_CANDIDATE"
    MULTI_COMMITTEE_STATEMENT_CONFLICT = (
        "MULTI_COMMITTEE_STATEMENT_CONFLICT"
    )
    PRIOR_VS_CURRENT_STATEMENT_CONFLICT = (
        "PRIOR_VS_CURRENT_STATEMENT_CONFLICT"
    )
    CONFIDENCE_INSUFFICIENT = "CONFIDENCE_INSUFFICIENT"


class ContradictionCaseStatus(Enum):
    UNRESOLVED = "UNRESOLVED"
    STRUCTURALLY_CLEARED = "STRUCTURALLY_CLEARED"
    INELIGIBLE = "INELIGIBLE"


class NumericPathStatus(Enum):
    APPLIED = "APPLIED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    PARTIAL = "PARTIAL"


class ReResearchReasonCode(Enum):
    NUMERIC_CANDIDATE = "NUMERIC_CANDIDATE"
    MULTI_COMMITTEE_STATEMENT_CONFLICT = (
        "MULTI_COMMITTEE_STATEMENT_CONFLICT"
    )
    PRIOR_VS_CURRENT_STATEMENT_CONFLICT = (
        "PRIOR_VS_CURRENT_STATEMENT_CONFLICT"
    )
    CONFIDENCE_INSUFFICIENT = "CONFIDENCE_INSUFFICIENT"


class EscalationMarker(Enum):
    WAIT = "WAIT"
    MONITOR = "MONITOR"


class EscalationReasonCode(Enum):
    RE_RESEARCH_BUDGET_EXHAUSTED = (
        "RE_RESEARCH_BUDGET_EXHAUSTED"
    )
    NON_PROGRESS = "NON_PROGRESS"
    UNPLANABLE_REQUESTS = "UNPLANABLE_REQUESTS"


class ContradictionNotesCode(Enum):
    DOMAIN_NOT_ELIGIBLE = "DOMAIN_NOT_ELIGIBLE"
