from __future__ import annotations


# Frozen HIP V1 vocabulary — encode exactly; do not invent alternate modes here.

DEPLOYABLE_CAPITAL_MODE_ORDERABLE_CASH_FULL = "ORDERABLE_CASH_FULL"
CAPITAL_SOURCING_MODE_ROTATION_ALLOWED = "ROTATION_ALLOWED"
ON_INVALIDATE_THESIS_BLOCK_AND_ALLOW_REDUCE_LEGS = "BLOCK_AND_ALLOW_REDUCE_LEGS"
PROFIT_REALIZATION_MODE_DEFER = "DEFER"

CURRENCY_KRW = "KRW"
AMOUNT_PRESENCE_PRESENT = "present"
AMOUNT_PRESENCE_MISSING = "missing"

ALLOCATION_ACTION_INCREASE = "INCREASE"
ALLOCATION_ACTION_MAINTAIN = "MAINTAIN"
ALLOCATION_ACTION_REDUCE = "REDUCE"
ALLOCATION_ACTION_EXIT = "EXIT"

APPROVAL_DECISION_APPROVED = "APPROVED"
APPROVAL_DECISION_REJECTED = "REJECTED"
APPROVAL_DECISION_NEEDS_REVISION = "NEEDS_REVISION"

CONSTRAINT_PASS = "PASS"
CONSTRAINT_FAIL = "FAIL"

FAILURE_MISSING_ORDERABLE_CASH = "MISSING_ORDERABLE_CASH"
FAILURE_FORBIDDEN_ACCOUNT_VALUATION_DENOMINATOR = "FORBIDDEN_ACCOUNT_VALUATION_DENOMINATOR"
FAILURE_NON_KRW_CURRENCY = "NON_KRW_CURRENCY"
FAILURE_LEVERAGE_PROHIBITED = "LEVERAGE_PROHIBITED"
FAILURE_RESERVE_NOT_EXPLICIT = "RESERVE_NOT_EXPLICIT"
FAILURE_RESERVE_POLICY_MISMATCH = "RESERVE_POLICY_MISMATCH"
FAILURE_MAX_POSITION_EXCEEDED = "MAX_POSITION_MARKET_VALUE_EXCEEDED"
FAILURE_INCREASE_CAPACITY_ZERO = "INCREASE_CAPACITY_ZERO"
FAILURE_WATCHLIST_ONLY_INELIGIBLE = "WATCHLIST_ONLY_INELIGIBLE"
FAILURE_SUBJECT_NOT_IN_UNIVERSE = "SUBJECT_NOT_IN_UNIVERSE"
FAILURE_POSTURE_BLOCKS_INCREASE = "POSTURE_BLOCKS_INCREASE"
FAILURE_ROTATION_REQUIRES_EV_SUPERIORITY = "ROTATION_REQUIRES_EV_SUPERIORITY"
FAILURE_ROTATION_PROCEEDS_INSUFFICIENT = "ROTATION_PROCEEDS_INSUFFICIENT"
FAILURE_CASH_CONSERVATION_VIOLATION = "CASH_CONSERVATION_VIOLATION"
FAILURE_DOUBLE_COUNT_ROTATION_PROCEEDS = "DOUBLE_COUNT_ROTATION_PROCEEDS"
FAILURE_CAPITAL_SNAPSHOT_MISMATCH = "CAPITAL_SNAPSHOT_MISMATCH"
FAILURE_HIP_INTEGRITY = "HIP_INTEGRITY_MISMATCH"
FAILURE_PROPOSAL_INTEGRITY = "PROPOSAL_INTEGRITY_MISMATCH"
FAILURE_APPROVAL_BINDING = "APPROVAL_BINDING_MISMATCH"
FAILURE_NEGATIVE_NOTIONAL = "NEGATIVE_NOTIONAL"
FAILURE_NONFINITE_DECIMAL = "NONFINITE_DECIMAL"
FAILURE_DUPLICATE_LEG = "DUPLICATE_LEG_OR_SUBJECT"
FAILURE_STRUCTURAL_LINK_INVALID = "STRUCTURAL_LINK_INVALID"
FAILURE_MISSING_CIO_POSTURE = "MISSING_CIO_POSTURE"
FAILURE_PROHIBITED_ORDER_PAYLOAD = "PROHIBITED_ORDER_PAYLOAD"
FAILURE_FLOAT_FORBIDDEN = "FLOAT_FORBIDDEN"

HIP_V1_POLICY_ID = "hip-v1-krw-domestic-cash-full"
HIP_V1_VERSION = "1"
