from __future__ import annotations


COMPOSITION_SOURCE_CLASS = "broker_fact"

PRODUCTION_RESULT_KIND_VALUES = ("success", "failure")

PRODUCTION_FAILURE_CODE_VALUES = (
    "MISSING_REQUIRED_FACT",
    "STALE_REQUIRED_FACT",
    "INELIGIBLE_FACT",
    "CRITERIA_MISMATCH",
    "PROJECTION_FAILURE",
)
