from enum import Enum


class PortfolioAllocationLegRiskBudgetLinkApplicabilityStatus(Enum):
    ALLOCATION_LEG_ENDPOINT_MISMATCH = "ALLOCATION_LEG_ENDPOINT_MISMATCH"
    RISK_BUDGET_ENDPOINT_MISMATCH = "RISK_BUDGET_ENDPOINT_MISMATCH"
    CAPITAL_BUCKET_ENDPOINT_MISMATCH = "CAPITAL_BUCKET_ENDPOINT_MISMATCH"
    POSITION_ENDPOINT_MISMATCH = "POSITION_ENDPOINT_MISMATCH"
    PORTFOLIO_ENDPOINT_MISMATCH = "PORTFOLIO_ENDPOINT_MISMATCH"
    APPLICABLE = "APPLICABLE"
