from __future__ import annotations


# Frozen C0-D1: LIMIT_ONLY — never emit market/conditionals.
ORDR_CCD_LIMIT = "00"
FORBIDDEN_ORDR_CCD = frozenset({"03", "12", "13", "M3"})

SIDE_BUY = "BUY"
SIDE_SELL = "SELL"

ORDER_INTENT_KIND_LIMIT = "LIMIT"

CURRENCY_KRW = "KRW"
AMOUNT_PRESENCE_PRESENT = "present"
AMOUNT_PRESENCE_MISSING = "missing"

# Instrument identity
HOLDINGS_IS_CD_PREFIX = "A"
SSAM_IS_CD_PATTERN_LEN = 6

# Provider READ request kinds (additive; holdings/balances preserved).
REQUEST_KIND_HOLDINGS = "holdings"
REQUEST_KIND_BALANCES = "balances"
REQUEST_KIND_ACCOUNT_STATE = "account_state"
REQUEST_KIND_QUOTE = "quote"
REQUEST_KIND_ORDER_STATUS = "order_status"
REQUEST_KIND_SELL_ORDERABILITY = "sell_orderability"
REQUEST_KIND_CASH_ORDERABILITY = "cash_orderability"

# KB API paths (READ only in ProviderGateway; mutation separate + mock).
API_PATH_IVU10140 = "/api/v1/ivu10140"
API_PATH_SSQM1801 = "/api/v1/ssqm1801"
API_PATH_SSQM1802 = "/api/v1/ssqm1802"
API_PATH_SSQM2341 = "/api/v1/ssqm2341"
API_PATH_SSQM0004 = "/api/v1/ssqm0004"
API_PATH_SSQM2952 = "/api/v1/ssqm2952"
API_PATH_SSAM1801 = "/api/v1/ssam1801"
API_PATH_SSAM1802 = "/api/v1/ssam1802"
API_PATH_SSAM1805 = "/api/v1/ssam1805"
API_PATH_SSAM1806 = "/api/v1/ssam1806"

# SSAM documented translation fields only (from KB samples).
SSAM_FIELD_GDS_NO1 = "gds_no1"
SSAM_FIELD_ORDR_UPRC = "ordr_uprc"
SSAM_FIELD_GNL_AC_NO1 = "gnl_ac_no1"
SSAM_FIELD_ORDR_JB_CLSF = "ordr_jb_clsf"
SSAM_FIELD_IS_CD = "is_cd"
SSAM_FIELD_ORDR_CCD = "ordr_ccd"
SSAM_FIELD_MKT_TM_CLSF = "mkt_tm_clsf"
SSAM_FIELD_ORDR_Q = "ordr_q"
SSAM_FIELD_CRDT_TYP_CD = "crdt_typ_cd"
SSAM_FIELD_SOR_ORDR_CCD = "sor_ordr_ccd"
SSAM_FIELD_S_CLSF = "s_clsf"
SSAM_FIELD_ORGN_ORDR_NO = "orgn_ordr_no"
SSAM_FIELD_CRCT_CLSF = "crct_clsf"

ORDR_JB_CLSF_SELL = "1"
ORDR_JB_CLSF_BUY = "2"
ORDR_JB_CLSF_MODIFY = "3"
ORDR_JB_CLSF_CANCEL = "4"
CRDT_TYP_CD_CASH = "00"
MKT_TM_CLSF_REGULAR = "1"

PROCESS_FLAG_ACCEPT = "A"
PROCESS_FLAG_REJECT = "B"

ACCEPTANCE_ACCEPTED = "ACCEPTED"
ACCEPTANCE_REJECTED = "REJECTED"
ACCEPTANCE_UNKNOWN = "SUBMISSION_OUTCOME_UNKNOWN"
ACCEPTANCE_NOT_READY = "MUTATION_NOT_READY"

RECOVERY_STATE_ONLY = "STATE_ONLY_RECOVERY"
RECOVERY_HUMAN_REQUIRED = "HUMAN_REQUIRED"
RECOVERY_AMBIGUOUS = "AMBIGUOUS"

MUTATION_TRANSPORT_MOCK = "MOCK"
MUTATION_TRANSPORT_LIVE_DISABLED = "LIVE_DISABLED"

ACCOUNT_BINDING_UNVERIFIED = "UNVERIFIED"
ACCOUNT_BINDING_VERIFIED = "VERIFIED"

FILL_CLAIM_NONE = "NO_FILL_CLAIM"
FILL_CLAIM_PARTIAL = "PARTIAL_FILL"
FILL_CLAIM_FULL = "FULL_FILL"
FILL_CLAIM_UNKNOWN = "FILL_UNKNOWN"

RECON_MATCH = "MATCH"
RECON_MISMATCH = "MISMATCH"
RECON_INCONCLUSIVE = "INCONCLUSIVE"

# Fail-closed codes
FAILURE_MISSING_TRADE_UNIT = "MISSING_OR_INVALID_TRADE_UNIT"
FAILURE_INVALID_LIMIT_PRICE = "INVALID_LIMIT_PRICE"
FAILURE_INVALID_QTY = "INVALID_DERIVED_QTY"
FAILURE_DERIVED_NOTIONAL_EXCEEDS_APPROVED = "DERIVED_NOTIONAL_EXCEEDS_APPROVED"
FAILURE_EXPOSURE_CAP = "EXPOSURE_CAP_EXCEEDED"
FAILURE_BUY_CASH_INSUFFICIENT = "BUY_CASH_INSUFFICIENT"
FAILURE_SELL_EXCEEDS_SELLABLE = "SELL_EXCEEDS_SELLABLE"
FAILURE_INSTRUMENT_UNPROVEN = "INSTRUMENT_IDENTITY_UNPROVEN"
FAILURE_ACCOUNT_UNVERIFIED = "ACCOUNT_BINDING_UNVERIFIED"
FAILURE_ORDR_CCD_FORBIDDEN = "ORDR_CCD_FORBIDDEN"
FAILURE_TEA_MISSING = "TEA_MISSING"
FAILURE_TEA_SEAL_MISMATCH = "TEA_SEAL_MISMATCH"
FAILURE_TEA_CONSUMED = "TEA_ONE_SHOT_CONSUMED"
FAILURE_TEA_REPLAY = "TEA_REPLAY"
FAILURE_PAYLOAD_HASH_MISMATCH = "PAYLOAD_HASH_MISMATCH"
FAILURE_LIVE_MUTATION_DISABLED = "LIVE_MUTATION_DISABLED"
FAILURE_IHA_INSUFFICIENT = "IHA_ALONE_INSUFFICIENT"
FAILURE_ALLOCATION_SEAL_MISMATCH = "ALLOCATION_SEAL_MISMATCH"
FAILURE_PRETRADE_STALE = "PRETRADE_STALE_OR_INVALID"
FAILURE_PRICE_CHANGED = "LIMIT_PRICE_CHANGED_INVALIDATES_TEA"
FAILURE_FLOAT_FORBIDDEN = "FLOAT_FORBIDDEN"
FAILURE_LEVERAGE_PROHIBITED = "LEVERAGE_PROHIBITED"
FAILURE_UNRESOLVED_SSAM_FIELD = "UNRESOLVED_SSAM_FIELD"
FAILURE_HTTP200_NOT_ACCEPT = "HTTP200_ALONE_NOT_ACCEPT"
FAILURE_ACCEPTANCE_AS_FILL = "ACCEPTANCE_IS_NOT_FILL"
FAILURE_AMBIGUOUS_RECOVERY = "AMBIGUOUS_RECOVERY_REQUIRES_HUMAN"
FAILURE_MISSING_PROPOSED_LIMIT_PRICE = "MISSING_PROPOSED_LIMIT_PRICE"
FAILURE_SIDE_INVALID = "SIDE_INVALID"
FAILURE_CANCEL_MODIFY_NOT_AUTO = "CANCEL_MODIFY_NO_AUTO_POLICY"

HIP_V1_MAX_EXPOSURE_KRW = "100000000"

BROKER_FIELD_NOW_PRC = "now_prc"
BROKER_FIELD_TRD_Q_UNT = "trd_q_unt"
BROKER_FIELD_ORDR_PSBL_CSH = "ordr_psbl_csh"
BROKER_FIELD_ORDR_PSBL_Q = "ordr_psbl_q"
BROKER_FIELD_PROCESS_FLAG = "processFlag"
BROKER_FIELD_ORDR_NO = "ordr_no"
BROKER_FIELD_IS_CD = "is_cd"
BROKER_FIELD_IS_NO = "is_no"
BROKER_FIELD_SHRT_CD = "shrt_cd"
